function(check expected)
    execute_process(COMMAND "${CLI}" ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(NOT result EQUAL expected)
        message(FATAL_ERROR "Expected exit ${expected}, got ${result}: ${stderr}")
    endif()
endfunction()
check(0 --help)
check(2)
check(2 --traj "${SOURCE}/data/sample_trajectory.csv" --unknown x)
check(2 --traj "${SOURCE}/data/sample_trajectory.csv" --max-speed nope)
check(2 --traj "${SOURCE}/data/sample_trajectory.csv" --max-speed -1)
check(2 --traj "${SOURCE}/data/sample_trajectory.csv" --traj duplicate)
check(2 --traj)
check(2 --traj "${SOURCE}/data/sample_trajectory.csv" --obs missing.csv)
check(2 --traj "${SOURCE}/data/sample_trajectory.csv" --out "${OUTPUT}/missing/report.json")
check(0 --traj "${SOURCE}/data/sample_trajectory.csv" --obs "${SOURCE}/data/sample_obstacles.csv" --out "${OUTPUT}")
file(READ "${OUTPUT}" first)
string(JSON version GET "${first}" schema_version)
string(JSON result GET "${first}" summary result)
if(NOT version EQUAL 2 OR NOT result STREQUAL "FAIL")
    message(FATAL_ERROR "Unexpected report schema or summary")
endif()
check(0 --traj "${SOURCE}/data/sample_trajectory.csv" --obs "${SOURCE}/data/sample_obstacles.csv" --out "${OUTPUT}")
file(READ "${OUTPUT}" second)
if(NOT first STREQUAL second)
    message(FATAL_ERROR "Report is nondeterministic")
endif()
check(3 --traj "${SOURCE}/data/sample_trajectory.csv" --fail-on-violation)
check(0 --traj "${SOURCE}/data/sample_trajectory.csv" --lane_half_width 100 --max_speed 100 --max_accel 100)
