execute_process(COMMAND "${LANE}" --synthetic --output "${OUTPUT}/lanes" RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Synthetic lane demo failed: ${error}")
endif()
execute_process(COMMAND "${LANE}" --input "${SOURCE}/data/synthetic_road.png" --output "${OUTPUT}/lanes-input" RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Image lane demo failed: ${error}")
endif()
execute_process(COMMAND "${LANE}" --synthetic --input invalid --output "${OUTPUT}" RESULT_VARIABLE result)
if(NOT result EQUAL 2)
    message(FATAL_ERROR "Lane demo accepted conflicting input options")
endif()
execute_process(COMMAND "${VISUALIZE}" --traj "${SOURCE}/data/dynamic_trajectory.csv" --obs "${SOURCE}/data/dynamic_obstacles.csv" --frames "${OUTPUT}/frames" --out "${OUTPUT}/report.json" RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Scenario visualization failed: ${error}")
endif()
file(GLOB frames "${OUTPUT}/frames/frame_*.png")
list(LENGTH frames count)
if(NOT count EQUAL 6 OR NOT EXISTS "${OUTPUT}/lanes/pipeline.png")
    message(FATAL_ERROR "Missing demo artifacts")
endif()
file(READ "${OUTPUT}/report.json" report)
string(JSON version GET "${report}" schema_version)
if(NOT version EQUAL 2)
    message(FATAL_ERROR "Invalid visualizer JSON report")
endif()
